@CommunityDailyDiary_Api_HostAddress = http://localhost:5123

GET {{CommunityDailyDiary_Api_HostAddress}}/api/posts/6797acbcf04dbce7a8113a9f
Accept: application/json

###
GET {{CommunityDailyDiary_Api_HostAddress}}/api/posts?date=01-27-2025
Accept: application/json

###
POST {{CommunityDailyDiary_Api_HostAddress}}/api/posts
Accept: application/json
Content-Type: application/json

{
  "title": "Sample Title",
  "body": "This is the body of the post.",
  "vote": 0
}

###
PATCH {{CommunityDailyDiary_Api_HostAddress}}/api/posts/6797acbcf04dbce7a8113a9f
Accept: application/json
Content-Type: application/json

{
  "voteUp": true
}